### ISSUE TITLE
Comments collection eagerly loaded for commentsCount

### ISSUE THREAD

**Issue by AfshinHonari** [AliBayat/Laravel-Commentable#1]
Comments in https://github.com/AliBayat/Laravel-Commentable/blob/edb1cb091e52cca2eae3555b8a356cb6820ef472/src/Commentable.php#L100 are eagerly loaded, only for counting comments (comments() function is better for this use-case).

**Comment by AliBayat** [comment]
when we use eager loading in the first place... then we already have the comments collection.. 
that we can easily count
so it's not a good practice to eager load another extra relationship.
